module.exports = {
    //ERROR
    USERNAME_OR_PASSWORD_INCORRECT: "Tài khoản hoặc mật khẩu không đúng",
    USERNAME_ALREADY_TAKEN: "Tài khoản đã tồn tại",
    USERNAME_NOT_FOUND: "Không tìm thấy người dùng",
    EMAIL_ALREADY_TAKEN: "Email đã tồn tại",
    EMAIL_INCORRECT_FORMAT: "Email không đúng định dạng",
    EMAIL_IS_NOT_CONFIRM: "Tài khoản chưa xác nhận Email,vui lòng kiểm tra lại",
    INTERVAL_SERVER: "Lỗi không xác định",
    NEWS_NOT_FOUND: "Không tìm thấy tin đăng",
    PHONE_IS_NOT_VALID: "Số điện thoại không đúng định dạng",
    FORBIDDEN_403: "Truy cập bị cấm",
    IMG_IS_NOT_VALID: "Hình ảnh không đúng định dạng base64",
    IMG_AND_CONTENT_IS_REQUIRED: "Hình ảnh và nội dung báo cáo không được trống cùng một lúc",
    REPORTS_NOT_FOUND: "Không tìm thấy danh sách báo cáo",
    WISH_LIST_ADD_FAILED: "Yêu thích thất bại",
    WISH_LIST_NOT_FOUND: "Không tìm thấy tin yêu thích",
    REPORT_FAILED: "Bạn đã báo cáo rồi,vui lòng chờ xác nhận",
    REPORT_NOT_FOUND: "Báo cáo không tồn tại",
    //RESULT SUCCESSFULLY
    REGISTER_SUCCESSFULLY: "Đăng ký thành công",
    LOGIN_SUCCESSFULLY: "Đăng nhập thành công",
    INF_SUCCESSFULLY: "Thành công",
    UPDATE_SUCCESSFULLY: "Cập nhật thành công",
    WISH_LIST_ADD_SUCCESSFULLY: "Yêu thích thành công",
    WISH_LIST_REMOVE_SUCCESSFULLY: "Hủy Yêu thích thành công",
}